const APIEntry = 'http://127.0.0.1:7001/'
const API_LIVE_STATUS = APIEntry + 'live/status'
const API_LIVE_CREATE = APIEntry + 'live/create'
const API_LIVE_MESSAGE = APIEntry + 'live/message'
const API_LIVE_LINKS = APIEntry + 'live/links'
const API_LIVE_LINK = APIEntry + 'live/link'
const API_USER_LOGIN = APIEntry + 'auth/jwt/login'
const API_USER_REGISTER = APIEntry + 'auth/register'
const API_USER_ME = APIEntry + 'users/me'
const API_CHATGPT_TOKEN = APIEntry + 'chatgpt/token'
const API_TRANSFER_ENTRIES = APIEntry + 'transfer/entries'
const API_USER_ALL = APIEntry + 'manage/users'
const API_USER = APIEntry + 'users'

export default { API_LIVE_STATUS, API_LIVE_LINK, API_LIVE_LINKS, API_USER_LOGIN, API_USER_REGISTER, API_LIVE_MESSAGE, API_LIVE_CREATE, API_TRANSFER_ENTRIES, API_USER_ME, API_CHATGPT_TOKEN, API_USER_ALL, API_USER }